// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6T2zf1SNwATDJFbFbIPdwmO41KdzVYQ',
    appId: '1:310754939872:web:65baa63ac3978026ec9185',
    messagingSenderId: '310754939872',
    projectId: 'muj-hackathon',
    authDomain: 'muj-hackathon.firebaseapp.com',
    storageBucket: 'muj-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTWLiwb6maQ1Fe__gWA8aSaZ3RgHDem0',
    appId: '1:310754939872:android:7b0d9b2128009133ec9185',
    messagingSenderId: '310754939872',
    projectId: 'muj-hackathon',
    storageBucket: 'muj-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxyn_NQTFeSFqhjoX2kMIo81XLemd1T0',
    appId: '1:310754939872:ios:2ebccb5abf0c70f9ec9185',
    messagingSenderId: '310754939872',
    projectId: 'muj-hackathon',
    storageBucket: 'muj-hackathon.appspot.com',
    iosClientId: '310754939872-98cvcn2p5493l67l9gblp1m9rnt8fovt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mujhackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlxyn_NQTFeSFqhjoX2kMIo81XLemd1T0',
    appId: '1:310754939872:ios:2ebccb5abf0c70f9ec9185',
    messagingSenderId: '310754939872',
    projectId: 'muj-hackathon',
    storageBucket: 'muj-hackathon.appspot.com',
    iosClientId: '310754939872-98cvcn2p5493l67l9gblp1m9rnt8fovt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mujhackathon',
  );
}
